// src/components/AmrapTargets.tsx
import type { AmrapTarget } from '../lib/calc'

interface Props {
  targets: AmrapTarget[]
}

export default function AmrapTargets({ targets }: Props) {
  if (targets.length === 0) return null
  return (
    <div className="mt-1 space-y-0.5">
      {targets.map(t => (
        <div key={t.label} className="text-xs text-warn font-mono">
          -&gt; {t.label.toUpperCase().padEnd(14)} {t.reps} reps{' '}
          <span className="text-muted">({t.est1RM}lb est. 1RM)</span>
        </div>
      ))}
    </div>
  )
}

// src-solid/components/AmrapTargets.tsx
import { For, Show } from 'solid-js'
import type { AmrapTarget } from '../../src/lib/calc'

interface Props {
  targets: AmrapTarget[]
}

export default function AmrapTargets(props: Props) {
  return (
    <Show when={props.targets.length > 0}>
      <div class="mt-1 space-y-0.5">
        <For each={props.targets}>
          {t => (
            <div class="text-xs text-warn font-mono">
              -&gt; {t.label.toUpperCase().padEnd(14)} {t.reps} reps{' '}
              <span class="text-muted">({t.est1RM}lb est. 1RM)</span>
            </div>
          )}
        </For>
      </div>
    </Show>
  )
}
