// src/App.tsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { lazy, Suspense, useEffect, useState } from 'react'
import { seedDatabase } from './db/seed'
import { db } from './db/db'
import { importFromRawData } from './lib/exportImport'
import { useSettingsStore } from './store/settingsStore'
import { useWorkoutStore } from './store/workoutStore'
import { useSwipeNav } from './hooks/useSwipeNav'
import BottomNav from './components/BottomNav'
import Setup from './screens/Setup'
import Today from './screens/Today'
import Workout from './screens/Workout'

const History = lazy(() => import('./screens/History'))
const HistoryEdit = lazy(() => import('./screens/HistoryEdit'))
const Settings = lazy(() => import('./screens/Settings'))

function AppShell() {
  const activeSession = useWorkoutStore((s) => s.activeSession)
  const { onTouchStart, onTouchEnd } = useSwipeNav()

  return (
    <div
      className="bg-bg min-h-screen font-mono text-text flex flex-col"
      style={{ paddingTop: 'env(safe-area-inset-top, 0px)' }}
    >
      <main
        className="flex-1 overflow-y-auto"
        style={{ paddingBottom: 'calc(env(safe-area-inset-bottom, 0px) + 3.5rem)' }}
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        <Suspense>
          <Routes>
            <Route path="/" element={<Navigate to={activeSession ? '/workout' : '/today'} replace />} />
            <Route path="/today" element={<Today />} />
            <Route path="/workout" element={<Workout />} />
            <Route path="/history" element={<History />} />
            <Route path="/history/:sessionId/edit" element={<HistoryEdit />} />
            <Route path="/settings" element={<Settings />} />
          </Routes>
        </Suspense>
      </main>
      <BottomNav />
    </div>
  )
}

export default function App() {
  const loadSettings = useSettingsStore((s) => s.load)
  const [setupComplete, setSetupComplete] = useState<boolean | null>(null)

  useEffect(() => {
    const init = async () => {
      if (import.meta.env.VITE_DEMO) {
        const isEmpty = (await db.trainingMaxes.count()) === 0
        if (isEmpty) {
          const res = await fetch('/demo-seed.json')
          await importFromRawData(await res.json())
        }
      }
      await seedDatabase()
      await loadSettings()
      const tmCount = await db.trainingMaxes.count()
      setSetupComplete(tmCount > 0)
    }
    init()
  }, [])

  if (setupComplete === null) return null

  if (!setupComplete) {
    return (
      <div className="bg-bg min-h-screen font-mono text-text">
        <Setup onComplete={() => setSetupComplete(true)} />
      </div>
    )
  }

  return (
    <BrowserRouter>
      <AppShell />
    </BrowserRouter>
  )
}

// src-solid/App.tsx
import { Router, Route, useNavigate, useLocation } from '@solidjs/router'
import { lazy, Suspense, Show, onMount, type ParentProps } from 'solid-js'
import BottomNav from './components/BottomNav'
import { db } from '../src/db/db-v2'

const ScreenFallback = () => (
  <div class="flex items-center justify-center h-full min-h-[50vh] text-text/40 text-sm">
    Loading…
  </div>
)

const Today = lazy(() => import('./screens/Today'))
const Workout = lazy(() => import('./screens/Workout'))
const History = lazy(() => import('./screens/History'))
const HistoryEdit = lazy(() => import('./screens/HistoryEdit'))
const Settings = lazy(() => import('./screens/Settings'))
const Setup = lazy(() => import('./screens/Setup'))

function AppShell(props: ParentProps) {
  const navigate = useNavigate()
  const location = useLocation()

  onMount(async () => {
    if (location.pathname !== '/setup') {
      const count = await db.trainingMaxes.count()
      if (count === 0) navigate('/setup', { replace: true })
    }
  })

  return (
    <div
      class="bg-bg min-h-screen font-mono text-text flex flex-col"
      style={{ 'padding-top': 'env(safe-area-inset-top, 0px)' }}
    >
      <main
        class="flex-1 overflow-y-auto"
        style={{ 'padding-bottom': 'calc(env(safe-area-inset-bottom, 0px) + 3.5rem)' }}
      >
        <Suspense fallback={<ScreenFallback />}>
          {props.children}
        </Suspense>
      </main>
      <Show when={location.pathname !== '/setup'}>
        <BottomNav />
      </Show>
    </div>
  )
}

export default function App() {
  return (
    <Router root={AppShell}>
      <Route path="/" component={Today} />
      <Route path="/today" component={Today} />
      <Route path="/workout" component={Workout} />
      <Route path="/history" component={History} />
      <Route path="/history/:sessionId/edit" component={HistoryEdit} />
      <Route path="/settings" component={Settings} />
      <Route path="/setup" component={Setup} />
    </Router>
  )
}
