// src/components/layout/BottomNav.tsx
import { A } from '@solidjs/router'
import { Show } from 'solid-js'
import { workout } from '../../store/workout-store'

export default function BottomNav() {
  return (
    <nav
      class="fixed bottom-0 left-0 right-0 bg-bg border-t border-border flex"
      style={{ 'padding-bottom': 'env(safe-area-inset-bottom, 0px)' }}
    >
      <A
        href="/today"
        class="flex-1 py-4 text-center text-xs tracking-widest transition-colors"
        activeClass="text-accent border-t border-accent -mt-px"
        inactiveClass="text-muted hover:text-text"
      >
        TODAY
      </A>
      <A
        href="/workout"
        class="flex-1 py-4 text-center text-xs tracking-widest transition-colors inline-flex items-center justify-center gap-1"
        activeClass="text-accent border-t border-accent -mt-px"
        inactiveClass="text-muted hover:text-text"
      >
        WORKOUT
        <Show when={workout.activeSession !== null}>
          <span class="w-1.5 h-1.5 rounded-full bg-accent inline-block" />
        </Show>
      </A>
      <A
        href="/history"
        end={false}
        class="flex-1 py-4 text-center text-xs tracking-widest transition-colors"
        activeClass="text-accent border-t border-accent -mt-px"
        inactiveClass="text-muted hover:text-text"
      >
        HISTORY
      </A>
      <A
        href="/settings"
        class="flex-1 py-4 text-center text-xs tracking-widest transition-colors"
        activeClass="text-accent border-t border-accent -mt-px"
        inactiveClass="text-muted hover:text-text"
      >
        SETTINGS
      </A>
    </nav>
  )
}

// src/components/BottomNav.tsx
import { NavLink } from 'react-router-dom'

const tabs = [
  { to: '/today',    label: 'TODAY'    },
  { to: '/workout',  label: 'WORKOUT'  },
  { to: '/history',  label: 'HISTORY'  },
  { to: '/settings', label: 'SETTINGS' },
]

export default function BottomNav() {
  return (
    <nav
      className="fixed bottom-0 left-0 right-0 bg-bg border-t border-border flex"
      style={{ paddingBottom: 'env(safe-area-inset-bottom, 0px)' }}
    >
      {tabs.map(({ to, label }) => (
        <NavLink
          key={to}
          to={to}
          className={({ isActive }) =>
            `flex-1 py-4 text-center text-xs tracking-widest transition-colors ${
              isActive
                ? 'text-accent border-t border-accent -mt-px'
                : 'text-muted hover:text-text'
            }`
          }
        >
          {label}
        </NavLink>
      ))}
    </nav>
  )
}
