// src-solid/components/PlateDisplay.tsx
import { createMemo, Show } from 'solid-js'
import { settings } from '../store/settingsStore'
import { calcPlatesPerSide } from '../../src/lib/calc'

interface Props {
  weight: number
}

export default function PlateDisplay(props: Props) {
  const result = createMemo(() => calcPlatesPerSide(props.weight, settings.barWeight, settings.plates))

  const items = createMemo(() => {
    const r = result()
    if (!r) return null
    const out: number[] = []
    for (const { weight: w, count } of r) {
      for (let i = 0; i < count; i++) out.push(w)
    }
    return out
  })

  return (
    <Show when={result() !== null}>
      <div class="text-faint text-xs font-mono mt-1">
        <Show
          when={items()!.length > 0}
          fallback="bar only"
        >
          {`each side: ${items()!.join(' · ')}`}
        </Show>
      </div>
    </Show>
  )
}

// src/components/PlateDisplay.tsx
import { useSettingsStore } from '../store/settingsStore'
import { calcPlatesPerSide } from '../lib/calc'

interface Props {
  weight: number
}

export default function PlateDisplay({ weight }: Props) {
  const { barWeight, plates } = useSettingsStore()
  const result = calcPlatesPerSide(weight, barWeight, plates)
  if (result === null) return null

  if (result.length === 0) {
    return (
      <div className="text-faint text-xs font-mono mt-1">bar only</div>
    )
  }

  const items: number[] = []
  for (const { weight: w, count } of result) {
    for (let i = 0; i < count; i++) items.push(w)
  }

  return (
    <div className="text-faint text-xs font-mono mt-1">
      {`each side: ${items.join(' · ')}`}
    </div>
  )
}
